// Code generated by candi v1.8.8.

package resthandler

import (
	"github.com/labstack/echo"

	"monorepo/services/seaotter/pkg/constant"
	"monorepo/services/seaotter/pkg/shared/usecase"

	"github.com/Bhinneka/candi/codebase/factory/dependency"
	"github.com/Bhinneka/candi/codebase/interfaces"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root *echo.Group) {
	masterV2 := root.Group("")

	// so prefix
	masterV2.GET(constant.RouteMasterSOPrefixV2, h.GetSOPrefix)
	masterV2.POST(constant.RouteMasterSOPrefixV2, nil)

}
