// Code generated by candi v1.8.8.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	masterusecase "monorepo/services/seaotter/internal/modules/master/usecase"
	salesorderusecase "monorepo/services/seaotter/internal/modules/salesorder/usecase"
	"monorepo/services/seaotter/pkg/shared/usecase/common"

	"github.com/Bhinneka/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		Master() masterusecase.MasterUsecase
		Salesorder() salesorderusecase.SalesorderUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		masterusecase.MasterUsecase
		salesorderusecase.SalesorderUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.MasterUsecase, setSharedUsecaseFunc = masterusecase.NewMasterUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.SalesorderUsecase, setSharedUsecaseFunc = salesorderusecase.NewSalesorderUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) Master() masterusecase.MasterUsecase {
	return uc.MasterUsecase
}

func (uc *usecaseUow) Salesorder() salesorderusecase.SalesorderUsecase {
	return uc.SalesorderUsecase
}
