// Code generated by candi v1.8.8. DO NOT EDIT.

package sdk

import (
	"sync"

	// @candi:serviceImport
	"monorepo/sdk/seaotter"
)

// Option func type
type Option func(*sdkInstance)

var (
	sdk  SDK
	once sync.Once
)

// SetGlobalSDK constructor with each sdk service option.
func SetGlobalSDK(opts ...Option) {
	s := new(sdkInstance)
	for _, o := range opts {
		o(s)
	}
	once.Do(func() {
		sdk = s
	})
}

// GetSDK get global sdk instance
func GetSDK() SDK {
	return sdk
}

// @candi:construct

// SetSeaotter option func
func SetSeaotter(seaotter seaotter.Seaotter) Option {
	return func(s *sdkInstance) {
		s.seaotter = seaotter
	}
}

// SDK instance abstraction
type SDK interface {
	// @candi:serviceMethod
	Seaotter() seaotter.Seaotter
}

// sdkInstance implementation
type sdkInstance struct {
	// @candi:serviceField
	seaotter	seaotter.Seaotter
}

// @candi:instanceMethod
func (s *sdkInstance) Seaotter() seaotter.Seaotter {
	return s.seaotter
}
