// Code generated by candi v1.8.8.

package workerhandler

import (
	"context"
	"fmt"

	"monorepo/services/seaotter/pkg/shared/usecase"

	"github.com/Bhinneka/candi/tracer"

	"github.com/Bhinneka/candi/codebase/factory/dependency"
	"github.com/Bhinneka/candi/codebase/factory/types"
	"github.com/Bhinneka/candi/codebase/interfaces"
)

// RedisHandler struct
type RedisHandler struct {
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRedisHandler constructor
func NewRedisHandler(uc usecase.Usecase, deps dependency.Dependency) *RedisHandler {
	return &RedisHandler{
		uc:        uc,
		validator: deps.GetValidator(),
	}
}

// MountHandlers mount handler group
func (h *RedisHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("salesorder-sample", h.handleSalesorder)
}

func (h *RedisHandler) handleSalesorder(ctx context.Context, message []byte) error {
	trace, ctx := tracer.StartTraceWithContext(ctx, "SalesorderDeliveryRedis:Hello")
	defer trace.Finish()

	fmt.Println("redis subs: execute sample")
	return nil
}
