// Code generated by candi v1.8.8. DO NOT EDIT.

package repository

import (
	"go.mongodb.org/mongo-driver/mongo"

	// @candi:repositoryImport
	salesorderrepo "monorepo/services/seaotter/internal/modules/salesorder/repository"
)

type (
	// RepoMongo abstraction
	RepoMongo interface {
		// @candi:repositoryMethod
		SalesorderRepo() salesorderrepo.SalesorderRepository
	}

	repoMongoImpl struct {
		readDB, writeDB *mongo.Database

		// register all repository from modules
		// @candi:repositoryField
		salesorderRepo salesorderrepo.SalesorderRepository
	}
)

var globalRepoMongo RepoMongo

// setSharedRepoMongo set the global singleton "RepoMongo" implementation
func setSharedRepoMongo(readDB, writeDB *mongo.Database) {
	globalRepoMongo = &repoMongoImpl{
		readDB: readDB, writeDB: writeDB,

		// @candi:repositoryConstructor
		salesorderRepo: salesorderrepo.NewSalesorderRepoMongo(readDB, writeDB),
	}
}

// GetSharedRepoMongo returns the global singleton "RepoMongo" implementation
func GetSharedRepoMongo() RepoMongo {
	return globalRepoMongo
}

// @candi:repositoryImplementation
func (r *repoMongoImpl) SalesorderRepo() salesorderrepo.SalesorderRepository {
	return r.salesorderRepo
}

