// Code generated by candi v1.8.8.

package repository

import "gorm.io/gorm"

// SalesorderRepoSQL abstract interface
type SalesorderRepoSQL interface {
}

type salesorderRepoSQL struct {
	readDB, writeDB *gorm.DB
}

// NewSalesorderRepoSQL mongo repo constructor
func NewSalesorderRepoSQL(readDB, writeDB *gorm.DB) SalesorderRepoSQL {
	return &salesorderRepoSQL{
		readDB, writeDB,
	}
}
