// Code generated by candi v1.8.8.

package repository

import (
	"context"

	"monorepo/services/seaotter/internal/modules/salesorder/domain"
	shareddomain "monorepo/services/seaotter/pkg/shared/domain"
)

// SalesorderRepository abstract interface
type SalesorderRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterSalesorder) ([]shareddomain.Salesorder, error)
	Count(ctx context.Context, filter *domain.FilterSalesorder) int
	Find(ctx context.Context, filter *domain.FilterSalesorder) (shareddomain.Salesorder, error)
	Save(ctx context.Context, data *shareddomain.Salesorder) error
	Delete(ctx context.Context, id string) (err error)
}
