// Code generated by candi v1.8.8.

package model

import (
	"monorepo/services/seaotter/pkg/constant"
	"time"
)

// MasterSOPrefix model
type MasterSOPrefix struct {
	ID          int       `gorm:"column:id" json:"id"`
	Code        string    `gorm:"column:code" json:"code"`
	Description string    `gorm:"column:description" json:"description"`
	CreatedAt   time.Time `gorm:"column:createdAt" json:"createdAt"`
	ModifiedAt  time.Time `gorm:"column:modifiedAt" json:"modifiedAt"`
	Threshold   float64   `gorm:"column:threshold" json:"threshold"`
}

// TableName return table name of master model
func (MasterSOPrefix) TableName() string {
	return constant.TableMasterSOPrefix
}

// CollectionName return collection name of master model
func (MasterSOPrefix) CollectionName() string {
	return constant.TableMasterSOPrefix
}
