// Code generated by candi v1.8.8.

package model

import (
	"time"
)

// Salesorder model
type Salesorder struct {
	ID         string    `gorm:"column:id;type:varchar(255);primary_key" bson:"_id" json:"id"`
	Field      string    `gorm:"column:field;type:varchar(255)" bson:"field" json:"field"`
	CreatedAt  time.Time `gorm:"column:created_at" bson:"created_at" json:"created_at"`
	ModifiedAt time.Time `gorm:"column:modified_at" bson:"modified_at" json:"modified_at"`
}

// TableName return table name of Salesorder model
func (Salesorder) TableName() string {
	return "salesorders"
}

// CollectionName return collection name of Salesorder model
func (Salesorder) CollectionName() string {
	return "salesorders"
}
