// Code generated by candi v1.8.8.

package payload

import "github.com/Bhinneka/candi/candishared"

// RequestGetSOPrexif payload
type RequestGetSOPrexif struct {
	candishared.Filter
	Code string `json:"code"`
}
