// Code generated by candi v1.8.8.

package main

import (
	"fmt"
	"runtime/debug"

	_ "github.com/lib/pq"

	"github.com/Bhinneka/candi/config"

	"github.com/Bhinneka/candi/codebase/app"

	service "monorepo/services/seaotter/internal"
)

const serviceName = "seaotter"

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Printf("\x1b[31;1mFailed to start %s service: %v\x1b[0m\n", serviceName, r)
			fmt.Printf("Stack trace: \n%s\n", debug.Stack())
		}
	}()

	cfg := config.Init(serviceName)
	defer cfg.Exit()

	app.New(service.NewService(cfg)).Run()
}
