// Code generated by candi v1.8.8.

package repository

import (
	"context"

	"gorm.io/gorm"

	"monorepo/services/seaotter/internal/modules/master/domain"
	model "monorepo/services/seaotter/pkg/shared/domain"
)

// MasterRepoSQL abstract interface
type MasterRepoSQL interface {
	CountSOPrefix(ctx context.Context, filter domain.FilterGetAllSOPrefix) (int64, error)
	GetAllSOPrefix(ctx context.Context, filter domain.FilterGetAllSOPrefix) (data []model.MasterSOPrefix, err error)
}

type masterRepoSQL struct {
	readDB, writeDB *gorm.DB
}

// NewMasterRepoSQL mongo repo constructor
func NewMasterRepoSQL(readDB, writeDB *gorm.DB) MasterRepoSQL {
	return &masterRepoSQL{
		readDB, writeDB,
	}
}
